"""
Interaction Drift Monitor

A simple conceptual Python prototype for comparing early-session and
late-session text samples in sustained human-AI interaction.

This first version uses lightweight text preprocessing, keyword overlap,
and cosine similarity over word-frequency vectors.

Related research:
"Third-Space Cognition: Interaction-Level Dynamics in Sustained Human-AI Coupling"
Zenodo DOI: 10.5281/zenodo.18679265
"""

from collections import Counter
from pathlib import Path
import math
import re


EARLY_TEXT_FILE = Path("sample_early.txt")
LATE_TEXT_FILE = Path("sample_late.txt")
OUTPUT_FILE = Path("drift_report.md")


def preprocess_text(text: str) -> list[str]:
    """
    Convert text into a clean list of lowercase words.

    This is intentionally simple for the first prototype.
    Future versions may use sentence embeddings or NLP libraries.
    """
    text = text.lower()
    words = re.findall(r"\b[a-zA-Z']+\b", text)
    return words


def word_frequency(words: list[str]) -> Counter:
    """Count word frequencies."""
    return Counter(words)


def cosine_similarity(counter_a: Counter, counter_b: Counter) -> float:
    """
    Calculate cosine similarity between two word-frequency counters.

    Returns a value between 0 and 1:
    - 1 means very similar word distribution
    - 0 means no overlap
    """
    all_words = set(counter_a) | set(counter_b)

    dot_product = sum(counter_a[word] * counter_b[word] for word in all_words)
    magnitude_a = math.sqrt(sum(counter_a[word] ** 2 for word in all_words))
    magnitude_b = math.sqrt(sum(counter_b[word] ** 2 for word in all_words))

    if magnitude_a == 0 or magnitude_b == 0:
        return 0.0

    return dot_product / (magnitude_a * magnitude_b)


def keyword_overlap(words_a: list[str], words_b: list[str]) -> float:
    """
    Calculate simple keyword overlap between two text samples.

    Returns the percentage of shared unique words.
    """
    set_a = set(words_a)
    set_b = set(words_b)

    if not set_a or not set_b:
        return 0.0

    shared_words = set_a & set_b
    total_unique_words = set_a | set_b

    return len(shared_words) / len(total_unique_words)


def top_terms(counter: Counter, limit: int = 10) -> list[tuple[str, int]]:
    """Return the most common terms."""
    return counter.most_common(limit)


def interpret_similarity(score: float) -> str:
    """
    Provide a simple interpretation of similarity/drift.

    Lower similarity suggests higher drift.
    """
    if score >= 0.75:
        return "Low drift / high similarity"
    if score >= 0.45:
        return "Moderate drift / partial similarity"
    return "High drift / low similarity"


def generate_report(
    early_text: str,
    late_text: str,
    similarity_score: float,
    overlap_score: float,
    early_terms: list[tuple[str, int]],
    late_terms: list[tuple[str, int]],
) -> str:
    """Generate a markdown report."""
    drift_interpretation = interpret_similarity(similarity_score)

    report = [
        "# Interaction Drift Report",
        "",
        "This report was generated by `drift_monitor.py`.",
        "",
        "## Overview",
        "",
        "This prototype compares an early-session text sample with a late-session text sample",
        "to estimate basic lexical similarity and possible interaction drift.",
        "",
        "## Results",
        "",
        f"- Cosine similarity: `{similarity_score:.3f}`",
        f"- Keyword overlap: `{overlap_score:.3f}`",
        f"- Interpretation: **{drift_interpretation}**",
        "",
        "## Early Sample Top Terms",
        "",
    ]

    for term, count in early_terms:
        report.append(f"- {term}: {count}")

    report.extend(["", "## Late Sample Top Terms", ""])

    for term, count in late_terms:
        report.append(f"- {term}: {count}")

    report.extend(
        [
            "",
            "## Notes",
            "",
            "This is a lightweight prototype and should not be treated as a full semantic analysis.",
            "It uses word-frequency comparison rather than embeddings or deep NLP methods.",
            "Future versions may use sentence embeddings, model-based clustering, or longitudinal visualization.",
            "",
            "## Sample Lengths",
            "",
            f"- Early sample characters: {len(early_text)}",
            f"- Late sample characters: {len(late_text)}",
        ]
    )

    return "\n".join(report)


def main() -> None:
    if not EARLY_TEXT_FILE.exists() or not LATE_TEXT_FILE.exists():
        raise FileNotFoundError(
            "Missing sample files. Add `sample_early.txt` and `sample_late.txt` "
            "to the same folder as this script."
        )

    early_text = EARLY_TEXT_FILE.read_text(encoding="utf-8")
    late_text = LATE_TEXT_FILE.read_text(encoding="utf-8")

    early_words = preprocess_text(early_text)
    late_words = preprocess_text(late_text)

    early_counts = word_frequency(early_words)
    late_counts = word_frequency(late_words)

    similarity_score = cosine_similarity(early_counts, late_counts)
    overlap_score = keyword_overlap(early_words, late_words)

    report = generate_report(
        early_text=early_text,
        late_text=late_text,
        similarity_score=similarity_score,
        overlap_score=overlap_score,
        early_terms=top_terms(early_counts),
        late_terms=top_terms(late_counts),
    )

    OUTPUT_FILE.write_text(report, encoding="utf-8")

    print(f"Cosine similarity: {similarity_score:.3f}")
    print(f"Keyword overlap: {overlap_score:.3f}")
    print(f"Report written to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
